# This file was generated automatically by the Snowball to Python compiler
# http://snowballstem.org/

from .basestemmer import BaseStemmer
from .among import Among


class TamilStemmer(BaseStemmer):
    '''
    This class was automatically generated by a Snowball to Python compiler
    It implements the stemming algorithm defined by a snowball script.
    '''

    a_0 = [
        Among(u"\u0B95", -1, -1),
        Among(u"\u0B99", -1, -1),
        Among(u"\u0B9A", -1, -1),
        Among(u"\u0B9E", -1, -1),
        Among(u"\u0BA4", -1, -1),
        Among(u"\u0BA8", -1, -1),
        Among(u"\u0BAA", -1, -1),
        Among(u"\u0BAE", -1, -1),
        Among(u"\u0BAF", -1, -1),
        Among(u"\u0BB5", -1, -1)
    ]

    a_1 = [
        Among(u"\u0BA8\u0BCD\u0BA4", -1, -1),
        Among(u"\u0BA8\u0BCD\u0BA4\u0BCD", -1, -1),
        Among(u"\u0BA8\u0BCD", -1, -1)
    ]

    a_2 = [
        Among(u"\u0BBF", -1, -1),
        Among(u"\u0BC0", -1, -1),
        Among(u"\u0BC8", -1, -1)
    ]

    a_3 = [
        Among(u"\u0B95", -1, -1),
        Among(u"\u0B9A", -1, -1),
        Among(u"\u0B9F", -1, -1),
        Among(u"\u0BA4", -1, -1),
        Among(u"\u0BAA", -1, -1),
        Among(u"\u0BB1", -1, -1)
    ]

    a_4 = [
        Among(u"\u0B95", -1, -1),
        Among(u"\u0B9A", -1, -1),
        Among(u"\u0B9F", -1, -1),
        Among(u"\u0BA4", -1, -1),
        Among(u"\u0BAA", -1, -1),
        Among(u"\u0BB1", -1, -1)
    ]

    a_5 = [
        Among(u"\u0B95", -1, -1),
        Among(u"\u0B9A", -1, -1),
        Among(u"\u0B9F", -1, -1),
        Among(u"\u0BA4", -1, -1),
        Among(u"\u0BAA", -1, -1),
        Among(u"\u0BB1", -1, -1)
    ]

    a_6 = [
        Among(u"\u0BAF", -1, -1),
        Among(u"\u0BB0", -1, -1),
        Among(u"\u0BB2", -1, -1),
        Among(u"\u0BB3", -1, -1),
        Among(u"\u0BB4", -1, -1),
        Among(u"\u0BB5", -1, -1)
    ]

    a_7 = [
        Among(u"\u0B99", -1, -1),
        Among(u"\u0B9E", -1, -1),
        Among(u"\u0BA3", -1, -1),
        Among(u"\u0BA8", -1, -1),
        Among(u"\u0BA9", -1, -1),
        Among(u"\u0BAE", -1, -1)
    ]

    a_8 = [
        Among(u"\u0BAF", -1, -1),
        Among(u"\u0BB5", -1, -1),
        Among(u"\u0BB5\u0BCD", -1, -1)
    ]

    a_9 = [
        Among(u"\u0BBE", -1, -1),
        Among(u"\u0BBF", -1, -1),
        Among(u"\u0BC0", -1, -1),
        Among(u"\u0BC1", -1, -1),
        Among(u"\u0BC2", -1, -1),
        Among(u"\u0BC6", -1, -1),
        Among(u"\u0BC7", -1, -1),
        Among(u"\u0BC8", -1, -1)
    ]

    a_10 = [
        Among(u"\u0BBE", -1, -1),
        Among(u"\u0BBF", -1, -1),
        Among(u"\u0BC0", -1, -1),
        Among(u"\u0BC1", -1, -1),
        Among(u"\u0BC2", -1, -1),
        Among(u"\u0BC6", -1, -1),
        Among(u"\u0BC7", -1, -1),
        Among(u"\u0BC8", -1, -1)
    ]

    a_11 = [
        Among(u"\u0B85", -1, -1),
        Among(u"\u0B87", -1, -1),
        Among(u"\u0B89", -1, -1)
    ]

    a_12 = [
        Among(u"\u0B95", -1, -1),
        Among(u"\u0B99", -1, -1),
        Among(u"\u0B9A", -1, -1),
        Among(u"\u0B9E", -1, -1),
        Among(u"\u0BA4", -1, -1),
        Among(u"\u0BA8", -1, -1),
        Among(u"\u0BAA", -1, -1),
        Among(u"\u0BAE", -1, -1),
        Among(u"\u0BAF", -1, -1),
        Among(u"\u0BB5", -1, -1)
    ]

    a_13 = [
        Among(u"\u0B95", -1, -1),
        Among(u"\u0B9A", -1, -1),
        Among(u"\u0B9F", -1, -1),
        Among(u"\u0BA4", -1, -1),
        Among(u"\u0BAA", -1, -1),
        Among(u"\u0BB1", -1, -1)
    ]

    a_14 = [
        Among(u"\u0BBE", -1, -1),
        Among(u"\u0BC7", -1, -1),
        Among(u"\u0BCB", -1, -1)
    ]

    a_15 = [
        Among(u"\u0BAA\u0BBF", -1, -1),
        Among(u"\u0BB5\u0BBF", -1, -1)
    ]

    a_16 = [
        Among(u"\u0BBE", -1, -1),
        Among(u"\u0BBF", -1, -1),
        Among(u"\u0BC0", -1, -1),
        Among(u"\u0BC1", -1, -1),
        Among(u"\u0BC2", -1, -1),
        Among(u"\u0BC6", -1, -1),
        Among(u"\u0BC7", -1, -1),
        Among(u"\u0BC8", -1, -1)
    ]

    a_17 = [
        Among(u"\u0BAA\u0B9F\u0BCD\u0B9F", -1, -1),
        Among(u"\u0BAA\u0B9F\u0BCD\u0B9F\u0BA3", -1, -1),
        Among(u"\u0BA4\u0BBE\u0BA9", -1, -1),
        Among(u"\u0BAA\u0B9F\u0BBF\u0BA4\u0BBE\u0BA9", 2, -1),
        Among(u"\u0B95\u0BC1\u0BB0\u0BBF\u0BAF", -1, -1),
        Among(u"\u0BAA\u0B9F\u0BBF", -1, -1),
        Among(u"\u0BAA\u0BB1\u0BCD\u0BB1\u0BBF", -1, -1),
        Among(u"\u0BAA\u0B9F\u0BC1", -1, -1),
        Among(u"\u0BB5\u0BBF\u0B9F\u0BC1", -1, -1),
        Among(u"\u0BAA\u0B9F\u0BCD\u0B9F\u0BC1", -1, -1),
        Among(u"\u0BB5\u0BBF\u0B9F\u0BCD\u0B9F\u0BC1", -1, -1),
        Among(u"\u0BAA\u0B9F\u0BCD\u0B9F\u0BA4\u0BC1", -1, -1),
        Among(u"\u0BC6\u0BB2\u0BCD\u0BB2\u0BBE\u0BAE\u0BCD", -1, -1)
    ]

    a_18 = [
        Among(u"\u0B95", -1, -1),
        Among(u"\u0B9A", -1, -1),
        Among(u"\u0B9F", -1, -1),
        Among(u"\u0BA4", -1, -1),
        Among(u"\u0BAA", -1, -1),
        Among(u"\u0BB1", -1, -1)
    ]

    a_19 = [
        Among(u"\u0B95", -1, -1),
        Among(u"\u0B9A", -1, -1),
        Among(u"\u0B9F", -1, -1),
        Among(u"\u0BA4", -1, -1),
        Among(u"\u0BAA", -1, -1),
        Among(u"\u0BB1", -1, -1)
    ]

    a_20 = [
        Among(u"\u0BBE", -1, -1),
        Among(u"\u0BBF", -1, -1),
        Among(u"\u0BC0", -1, -1),
        Among(u"\u0BC1", -1, -1),
        Among(u"\u0BC2", -1, -1),
        Among(u"\u0BC6", -1, -1),
        Among(u"\u0BC7", -1, -1),
        Among(u"\u0BC8", -1, -1)
    ]

    a_21 = [
        Among(u"\u0BBE", -1, -1),
        Among(u"\u0BBF", -1, -1),
        Among(u"\u0BC0", -1, -1),
        Among(u"\u0BC1", -1, -1),
        Among(u"\u0BC2", -1, -1),
        Among(u"\u0BC6", -1, -1),
        Among(u"\u0BC7", -1, -1),
        Among(u"\u0BC8", -1, -1)
    ]

    a_22 = [
        Among(u"\u0BAA\u0B9F\u0BC1", -1, -1),
        Among(u"\u0B95\u0BCA\u0BA3\u0BCD\u0B9F\u0BBF\u0BB0\u0BCD", -1, -1)
    ]

    a_23 = [
        Among(u"\u0B85", -1, -1),
        Among(u"\u0B86", -1, -1),
        Among(u"\u0B87", -1, -1),
        Among(u"\u0B88", -1, -1),
        Among(u"\u0B89", -1, -1),
        Among(u"\u0B8A", -1, -1),
        Among(u"\u0B8E", -1, -1),
        Among(u"\u0B8F", -1, -1),
        Among(u"\u0B90", -1, -1),
        Among(u"\u0B92", -1, -1),
        Among(u"\u0B93", -1, -1),
        Among(u"\u0B94", -1, -1)
    ]

    a_24 = [
        Among(u"\u0BBE", -1, -1),
        Among(u"\u0BBF", -1, -1),
        Among(u"\u0BC0", -1, -1),
        Among(u"\u0BC1", -1, -1),
        Among(u"\u0BC2", -1, -1),
        Among(u"\u0BC6", -1, -1),
        Among(u"\u0BC7", -1, -1),
        Among(u"\u0BC8", -1, -1)
    ]

    a_25 = [
        Among(u"\u0B95\u0BBF\u0BB1", -1, -1),
        Among(u"\u0B95\u0BBF\u0BA9\u0BCD\u0BB1", -1, -1),
        Among(u"\u0BBE\u0BA8\u0BBF\u0BA9\u0BCD\u0BB1", -1, -1),
        Among(u"\u0B95\u0BBF\u0BB1\u0BCD", -1, -1),
        Among(u"\u0B95\u0BBF\u0BA9\u0BCD\u0BB1\u0BCD", -1, -1),
        Among(u"\u0BBE\u0BA8\u0BBF\u0BA9\u0BCD\u0BB1\u0BCD", -1, -1)
    ]

    I_length = 0
    B_found_wrong_ending = False
    B_found_vetrumai_urupu = False
    B_found_a_match = False


    def __r_has_min_length(self):
        # (, line 104
        self.I_length = len(self.current)
        if not self.I_length > 4:
            return False
        return True

    def __r_fix_va_start(self):
        # (, line 109
        # or, line 110
        try:
            v_1 = self.cursor
            try:
                # (, line 110
                # and, line 110
                v_2 = self.cursor
                # try, line 110
                v_3 = self.cursor
                try:
                    # literal, line 110
                    if not self.eq_s(u"\u0BB5\u0BCB"):
                        self.cursor = v_3
                        raise lab2()
                except lab2: pass
                self.cursor = v_2
                # [, line 110
                self.bra = self.cursor
                # literal, line 110
                if not self.eq_s(u"\u0BB5\u0BCB"):
                    raise lab1()
                # ], line 110
                self.ket = self.cursor
                # <-, line 110
                if not self.slice_from(u"\u0B93"):
                    return False
                raise lab0()
            except lab1: pass
            self.cursor = v_1
            try:
                # (, line 111
                # and, line 111
                v_4 = self.cursor
                # try, line 111
                v_5 = self.cursor
                try:
                    # literal, line 111
                    if not self.eq_s(u"\u0BB5\u0BCA"):
                        self.cursor = v_5
                        raise lab4()
                except lab4: pass
                self.cursor = v_4
                # [, line 111
                self.bra = self.cursor
                # literal, line 111
                if not self.eq_s(u"\u0BB5\u0BCA"):
                    raise lab3()
                # ], line 111
                self.ket = self.cursor
                # <-, line 111
                if not self.slice_from(u"\u0B92"):
                    return False
                raise lab0()
            except lab3: pass
            self.cursor = v_1
            try:
                # (, line 112
                # and, line 112
                v_6 = self.cursor
                # try, line 112
                v_7 = self.cursor
                try:
                    # literal, line 112
                    if not self.eq_s(u"\u0BB5\u0BC1"):
                        self.cursor = v_7
                        raise lab6()
                except lab6: pass
                self.cursor = v_6
                # [, line 112
                self.bra = self.cursor
                # literal, line 112
                if not self.eq_s(u"\u0BB5\u0BC1"):
                    raise lab5()
                # ], line 112
                self.ket = self.cursor
                # <-, line 112
                if not self.slice_from(u"\u0B89"):
                    return False
                raise lab0()
            except lab5: pass
            self.cursor = v_1
            # (, line 113
            # and, line 113
            v_8 = self.cursor
            # try, line 113
            v_9 = self.cursor
            try:
                # literal, line 113
                if not self.eq_s(u"\u0BB5\u0BC2"):
                    self.cursor = v_9
                    raise lab7()
            except lab7: pass
            self.cursor = v_8
            # [, line 113
            self.bra = self.cursor
            # literal, line 113
            if not self.eq_s(u"\u0BB5\u0BC2"):
                return False
            # ], line 113
            self.ket = self.cursor
            # <-, line 113
            if not self.slice_from(u"\u0B8A"):
                return False
        except lab0: pass
        return True

    def __r_fix_endings(self):
        # (, line 116
        # set found_wrong_ending, line 117
        self.B_found_wrong_ending = True
        # repeat, line 118
        try:
            while True:
                try:
                    v_1 = self.cursor
                    try:
                        # (, line 118
                        # Boolean test found_wrong_ending, line 118
                        if not self.B_found_wrong_ending:
                            raise lab2()
                        # (, line 118
                        # do, line 118
                        v_2 = self.cursor
                        try:
                            # call fix_ending, line 118
                            if not self.__r_fix_ending():
                                raise lab3()
                        except lab3: pass
                        self.cursor = v_2
                        raise lab1()
                    except lab2: pass
                    self.cursor = v_1
                    raise lab0()
                except lab1: pass
        except lab0: pass
        return True

    def __r_remove_question_prefixes(self):
        # (, line 121
        # [, line 122
        self.bra = self.cursor
        # (, line 122
        # literal, line 122
        if not self.eq_s(u"\u0B8E"):
            return False
        # among, line 122
        if self.find_among(TamilStemmer.a_0) == 0:
            return False
        # literal, line 122
        if not self.eq_s(u"\u0BCD"):
            return False
        # ], line 122
        self.ket = self.cursor
        # delete, line 122
        if not self.slice_del():
            return False

        # do, line 123
        v_1 = self.cursor
        try:
            # call fix_va_start, line 123
            if not self.__r_fix_va_start():
                raise lab0()
        except lab0: pass
        self.cursor = v_1
        return True

    def __r_fix_ending(self):
        # (, line 126
        # unset found_wrong_ending, line 127
        self.B_found_wrong_ending = False
        self.I_length = len(self.current)
        if not self.I_length > 3:
            return False
        # backwards, line 130
        self.limit_backward = self.cursor
        self.cursor = self.limit
        # (, line 130
        # or, line 132
        try:
            v_1 = self.limit - self.cursor
            try:
                # (, line 131
                # [, line 131
                self.ket = self.cursor
                # among, line 131
                if self.find_among_b(TamilStemmer.a_1) == 0:
                    raise lab1()
                # ], line 131
                self.bra = self.cursor
                # delete, line 131
                if not self.slice_del():
                    return False

                raise lab0()
            except lab1: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 133
                # [, line 133
                self.ket = self.cursor
                # literal, line 133
                if not self.eq_s_b(u"\u0BAF\u0BCD"):
                    raise lab2()
                # test, line 133
                v_2 = self.limit - self.cursor
                # among, line 133
                if self.find_among_b(TamilStemmer.a_2) == 0:
                    raise lab2()
                self.cursor = self.limit - v_2
                # ], line 133
                self.bra = self.cursor
                # delete, line 133
                if not self.slice_del():
                    return False

                raise lab0()
            except lab2: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 135
                # [, line 135
                self.ket = self.cursor
                # or, line 135
                try:
                    v_3 = self.limit - self.cursor
                    try:
                        # literal, line 135
                        if not self.eq_s_b(u"\u0B9F\u0BCD\u0BAA\u0BCD"):
                            raise lab5()
                        raise lab4()
                    except lab5: pass
                    self.cursor = self.limit - v_3
                    # literal, line 135
                    if not self.eq_s_b(u"\u0B9F\u0BCD\u0B95\u0BCD"):
                        raise lab3()
                except lab4: pass
                # ], line 135
                self.bra = self.cursor
                # <-, line 135
                if not self.slice_from(u"\u0BB3\u0BCD"):
                    return False
                raise lab0()
            except lab3: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 137
                # [, line 137
                self.ket = self.cursor
                # literal, line 137
                if not self.eq_s_b(u"\u0BA9\u0BCD\u0BB1\u0BCD"):
                    raise lab6()
                # ], line 137
                self.bra = self.cursor
                # <-, line 137
                if not self.slice_from(u"\u0BB2\u0BCD"):
                    return False
                raise lab0()
            except lab6: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 140
                # [, line 140
                self.ket = self.cursor
                # literal, line 140
                if not self.eq_s_b(u"\u0BB1\u0BCD\u0B95\u0BCD"):
                    raise lab7()
                # ], line 140
                self.bra = self.cursor
                # <-, line 140
                if not self.slice_from(u"\u0BB2\u0BCD"):
                    return False
                raise lab0()
            except lab7: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 142
                # [, line 142
                self.ket = self.cursor
                # literal, line 142
                if not self.eq_s_b(u"\u0B9F\u0BCD\u0B9F\u0BCD"):
                    raise lab8()
                # ], line 142
                self.bra = self.cursor
                # <-, line 142
                if not self.slice_from(u"\u0B9F\u0BC1"):
                    return False
                raise lab0()
            except lab8: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 144
                # Boolean test found_vetrumai_urupu, line 144
                if not self.B_found_vetrumai_urupu:
                    raise lab9()
                # [, line 144
                self.ket = self.cursor
                # literal, line 144
                if not self.eq_s_b(u"\u0BA4\u0BCD\u0BA4\u0BCD"):
                    raise lab9()
                # (, line 144
                # test, line 144
                v_4 = self.limit - self.cursor
                # not, line 144
                v_5 = self.limit - self.cursor
                try:
                    # literal, line 144
                    if not self.eq_s_b(u"\u0BC8"):
                        raise lab10()
                    raise lab9()
                except lab10: pass
                self.cursor = self.limit - v_5
                self.cursor = self.limit - v_4
                # ], line 144
                self.bra = self.cursor
                # <-, line 144
                if not self.slice_from(u"\u0BAE\u0BCD"):
                    return False
                # ], line 144
                self.bra = self.cursor
                raise lab0()
            except lab9: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 146
                # [, line 146
                self.ket = self.cursor
                # or, line 146
                try:
                    v_6 = self.limit - self.cursor
                    try:
                        # literal, line 146
                        if not self.eq_s_b(u"\u0BC1\u0B95\u0BCD"):
                            raise lab13()
                        raise lab12()
                    except lab13: pass
                    self.cursor = self.limit - v_6
                    # literal, line 146
                    if not self.eq_s_b(u"\u0BC1\u0B95\u0BCD\u0B95\u0BCD"):
                        raise lab11()
                except lab12: pass
                # ], line 146
                self.bra = self.cursor
                # <-, line 146
                if not self.slice_from(u"\u0BCD"):
                    return False
                raise lab0()
            except lab11: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 148
                # [, line 148
                self.ket = self.cursor
                # literal, line 148
                if not self.eq_s_b(u"\u0BCD"):
                    raise lab14()
                # among, line 148
                if self.find_among_b(TamilStemmer.a_3) == 0:
                    raise lab14()
                # literal, line 148
                if not self.eq_s_b(u"\u0BCD"):
                    raise lab14()
                # among, line 148
                if self.find_among_b(TamilStemmer.a_4) == 0:
                    raise lab14()
                # ], line 148
                self.bra = self.cursor
                # delete, line 148
                if not self.slice_del():
                    return False

                raise lab0()
            except lab14: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 150
                # [, line 150
                self.ket = self.cursor
                # literal, line 150
                if not self.eq_s_b(u"\u0BC1\u0B95\u0BCD"):
                    raise lab15()
                # ], line 150
                self.bra = self.cursor
                # <-, line 150
                if not self.slice_from(u"\u0BCD"):
                    return False
                raise lab0()
            except lab15: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 152
                # [, line 152
                self.ket = self.cursor
                # literal, line 152
                if not self.eq_s_b(u"\u0BCD"):
                    raise lab16()
                # among, line 152
                if self.find_among_b(TamilStemmer.a_5) == 0:
                    raise lab16()
                # ], line 152
                self.bra = self.cursor
                # delete, line 152
                if not self.slice_del():
                    return False

                raise lab0()
            except lab16: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 154
                # [, line 154
                self.ket = self.cursor
                # literal, line 154
                if not self.eq_s_b(u"\u0BCD"):
                    raise lab17()
                # (, line 154
                # or, line 154
                try:
                    v_7 = self.limit - self.cursor
                    try:
                        # among, line 154
                        if self.find_among_b(TamilStemmer.a_6) == 0:
                            raise lab19()
                        raise lab18()
                    except lab19: pass
                    self.cursor = self.limit - v_7
                    # among, line 154
                    if self.find_among_b(TamilStemmer.a_7) == 0:
                        raise lab17()
                except lab18: pass
                # literal, line 154
                if not self.eq_s_b(u"\u0BCD"):
                    raise lab17()
                # ], line 154
                self.bra = self.cursor
                # <-, line 154
                if not self.slice_from(u"\u0BCD"):
                    return False
                raise lab0()
            except lab17: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 156
                # [, line 156
                self.ket = self.cursor
                # among, line 156
                if self.find_among_b(TamilStemmer.a_8) == 0:
                    raise lab20()
                # ], line 156
                self.bra = self.cursor
                # delete, line 156
                if not self.slice_del():
                    return False

                raise lab0()
            except lab20: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 158
                # [, line 158
                self.ket = self.cursor
                # literal, line 158
                if not self.eq_s_b(u"\u0BA9\u0BC1"):
                    raise lab21()
                # (, line 158
                # test, line 158
                v_8 = self.limit - self.cursor
                # not, line 158
                v_9 = self.limit - self.cursor
                try:
                    # among, line 158
                    if self.find_among_b(TamilStemmer.a_9) == 0:
                        raise lab22()
                    raise lab21()
                except lab22: pass
                self.cursor = self.limit - v_9
                self.cursor = self.limit - v_8
                # ], line 158
                self.bra = self.cursor
                # delete, line 158
                if not self.slice_del():
                    return False

                raise lab0()
            except lab21: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 160
                # [, line 160
                self.ket = self.cursor
                # literal, line 160
                if not self.eq_s_b(u"\u0B99\u0BCD"):
                    raise lab23()
                # (, line 160
                # test, line 160
                v_10 = self.limit - self.cursor
                # not, line 160
                v_11 = self.limit - self.cursor
                try:
                    # literal, line 160
                    if not self.eq_s_b(u"\u0BC8"):
                        raise lab24()
                    raise lab23()
                except lab24: pass
                self.cursor = self.limit - v_11
                self.cursor = self.limit - v_10
                # ], line 160
                self.bra = self.cursor
                # <-, line 160
                if not self.slice_from(u"\u0BAE\u0BCD"):
                    return False
                raise lab0()
            except lab23: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 162
                # [, line 162
                self.ket = self.cursor
                # literal, line 162
                if not self.eq_s_b(u"\u0B99\u0BCD"):
                    raise lab25()
                # ], line 162
                self.bra = self.cursor
                # delete, line 162
                if not self.slice_del():
                    return False

                raise lab0()
            except lab25: pass
            self.cursor = self.limit - v_1
            # (, line 164
            # [, line 164
            self.ket = self.cursor
            # literal, line 164
            if not self.eq_s_b(u"\u0BCD"):
                return False
            # (, line 164
            # test, line 164
            v_12 = self.limit - self.cursor
            # (, line 164
            # or, line 164
            try:
                v_13 = self.limit - self.cursor
                try:
                    # among, line 164
                    if self.find_among_b(TamilStemmer.a_10) == 0:
                        raise lab27()
                    raise lab26()
                except lab27: pass
                self.cursor = self.limit - v_13
                # literal, line 164
                if not self.eq_s_b(u"\u0BCD"):
                    return False
            except lab26: pass
            self.cursor = self.limit - v_12
            # ], line 164
            self.bra = self.cursor
            # delete, line 164
            if not self.slice_del():
                return False

        except lab0: pass
        self.cursor = self.limit_backward
        # set found_wrong_ending, line 167
        self.B_found_wrong_ending = True
        return True

    def __r_remove_pronoun_prefixes(self):
        # (, line 170
        # unset found_a_match, line 171
        self.B_found_a_match = False
        # [, line 172
        self.bra = self.cursor
        # among, line 172
        if self.find_among(TamilStemmer.a_11) == 0:
            return False
        # among, line 172
        if self.find_among(TamilStemmer.a_12) == 0:
            return False
        # literal, line 172
        if not self.eq_s(u"\u0BCD"):
            return False
        # ], line 172
        self.ket = self.cursor
        # delete, line 172
        if not self.slice_del():
            return False

        # (, line 173
        # set found_a_match, line 173
        self.B_found_a_match = True
        # do, line 174
        v_1 = self.cursor
        try:
            # call fix_va_start, line 174
            if not self.__r_fix_va_start():
                raise lab0()
        except lab0: pass
        self.cursor = v_1
        return True

    def __r_remove_plural_suffix(self):
        # (, line 177
        # unset found_a_match, line 178
        self.B_found_a_match = False
        # backwards, line 179
        self.limit_backward = self.cursor
        self.cursor = self.limit
        # (, line 179
        # or, line 180
        try:
            v_1 = self.limit - self.cursor
            try:
                # (, line 180
                # [, line 180
                self.ket = self.cursor
                # literal, line 180
                if not self.eq_s_b(u"\u0BC1\u0B99\u0BCD\u0B95\u0BB3\u0BCD"):
                    raise lab1()
                # (, line 180
                # test, line 180
                v_2 = self.limit - self.cursor
                # not, line 180
                v_3 = self.limit - self.cursor
                try:
                    # among, line 180
                    if self.find_among_b(TamilStemmer.a_13) == 0:
                        raise lab2()
                    raise lab1()
                except lab2: pass
                self.cursor = self.limit - v_3
                self.cursor = self.limit - v_2
                # ], line 180
                self.bra = self.cursor
                # <-, line 180
                if not self.slice_from(u"\u0BCD"):
                    return False
                raise lab0()
            except lab1: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 181
                # [, line 181
                self.ket = self.cursor
                # literal, line 181
                if not self.eq_s_b(u"\u0BB1\u0BCD\u0B95\u0BB3\u0BCD"):
                    raise lab3()
                # ], line 181
                self.bra = self.cursor
                # <-, line 181
                if not self.slice_from(u"\u0BB2\u0BCD"):
                    return False
                raise lab0()
            except lab3: pass
            self.cursor = self.limit - v_1
            try:
                # (, line 182
                # [, line 182
                self.ket = self.cursor
                # literal, line 182
                if not self.eq_s_b(u"\u0B9F\u0BCD\u0B95\u0BB3\u0BCD"):
                    raise lab4()
                # ], line 182
                self.bra = self.cursor
                # <-, line 182
                if not self.slice_from(u"\u0BB3\u0BCD"):
                    return False
                raise lab0()
            except lab4: pass
            self.cursor = self.limit - v_1
            # (, line 183
            # [, line 183
            self.ket = self.cursor
            # literal, line 183
            if not self.eq_s_b(u"\u0B95\u0BB3\u0BCD"):
                return False
            # ], line 183
            self.bra = self.cursor
            # delete, line 183
            if not self.slice_del():
                return False

        except lab0: pass
        # (, line 184
        # set found_a_match, line 184
        self.B_found_a_match = True
        self.cursor = self.limit_backward
        return True

    def __r_remove_question_suffixes(self):
        # (, line 188
        # call has_min_length, line 189
        if not self.__r_has_min_length():
            return False
        # unset found_a_match, line 190
        self.B_found_a_match = False
        # backwards, line 191
        self.limit_backward = self.cursor
        self.cursor = self.limit
        # (, line 191
        # do, line 192
        v_1 = self.limit - self.cursor
        try:
            # (, line 192
            # [, line 193
            self.ket = self.cursor
            # among, line 193
            if self.find_among_b(TamilStemmer.a_14) == 0:
                raise lab0()
            # ], line 193
            self.bra = self.cursor
            # <-, line 193
            if not self.slice_from(u"\u0BCD"):
                return False
            # (, line 194
            # set found_a_match, line 194
            self.B_found_a_match = True
        except lab0: pass
        self.cursor = self.limit - v_1
        self.cursor = self.limit_backward
        # do, line 197
        v_2 = self.cursor
        try:
            # call fix_endings, line 197
            if not self.__r_fix_endings():
                raise lab1()
        except lab1: pass
        self.cursor = v_2
        return True

    def __r_remove_command_suffixes(self):
        # (, line 200
        # call has_min_length, line 201
        if not self.__r_has_min_length():
            return False
        # unset found_a_match, line 202
        self.B_found_a_match = False
        # backwards, line 203
        self.limit_backward = self.cursor
        self.cursor = self.limit
        # (, line 203
        # [, line 204
        self.ket = self.cursor
        # among, line 204
        if self.find_among_b(TamilStemmer.a_15) == 0:
            return False
        # ], line 204
        self.bra = self.cursor
        # delete, line 204
        if not self.slice_del():
            return False

        # (, line 205
        # set found_a_match, line 205
        self.B_found_a_match = True
        self.cursor = self.limit_backward
        return True

    def __r_remove_um(self):
        # (, line 209
        # unset found_a_match, line 210
        self.B_found_a_match = False
        # call has_min_length, line 211
        if not self.__r_has_min_length():
            return False
        # backwards, line 212
        self.limit_backward = self.cursor
        self.cursor = self.limit
        # (, line 212
        # [, line 212
        self.ket = self.cursor
        # literal, line 212
        if not self.eq_s_b(u"\u0BC1\u0BAE\u0BCD"):
            return False
        # ], line 212
        self.bra = self.cursor
        # <-, line 212
        if not self.slice_from(u"\u0BCD"):
            return False
        # (, line 213
        # set found_a_match, line 213
        self.B_found_a_match = True
        self.cursor = self.limit_backward
        # do, line 215
        v_1 = self.cursor
        try:
            # call fix_ending, line 215
            if not self.__r_fix_ending():
                raise lab0()
        except lab0: pass
        self.cursor = v_1
        return True

    def __r_remove_common_word_endings(self):
        # (, line 218
        # unset found_a_match, line 222
        self.B_found_a_match = False
        # call has_min_length, line 223
        if not self.__r_has_min_length():
            return False
        # backwards, line 224
        self.limit_backward = self.cursor
        self.cursor = self.limit
        # (, line 224
        # or, line 241
        try:
            v_1 = self.limit - self.cursor
            try:
                # test, line 225
                v_2 = self.limit - self.cursor
                # (, line 225
                # [, line 225
                self.ket = self.cursor
                # or, line 225
                try:
                    v_3 = self.limit - self.cursor
                    try:
                        # literal, line 225
                        if not self.eq_s_b(u"\u0BC1\u0B9F\u0BA9\u0BCD"):
                            raise lab3()
                        raise lab2()
                    except lab3: pass
                    self.cursor = self.limit - v_3
                    try:
                        # literal, line 226
                        if not self.eq_s_b(u"\u0BBF\u0BB2\u0BCD\u0BB2\u0BC8"):
                            raise lab4()
                        raise lab2()
                    except lab4: pass
                    self.cursor = self.limit - v_3
                    try:
                        # literal, line 227
                        if not self.eq_s_b(u"\u0BBF\u0B9F\u0BAE\u0BCD"):
                            raise lab5()
                        raise lab2()
                    except lab5: pass
                    self.cursor = self.limit - v_3
                    try:
                        # literal, line 228
                        if not self.eq_s_b(u"\u0BBF\u0BA9\u0BCD\u0BB1\u0BBF"):
                            raise lab6()
                        raise lab2()
                    except lab6: pass
                    self.cursor = self.limit - v_3
                    try:
                        # literal, line 229
                        if not self.eq_s_b(u"\u0BBE\u0B95\u0BBF"):
                            raise lab7()
                        raise lab2()
                    except lab7: pass
                    self.cursor = self.limit - v_3
                    try:
                        # literal, line 230
                        if not self.eq_s_b(u"\u0BBE\u0B95\u0BBF\u0BAF"):
                            raise lab8()
                        raise lab2()
                    except lab8: pass
                    self.cursor = self.limit - v_3
                    try:
                        # literal, line 231
                        if not self.eq_s_b(u"\u0BC6\u0BA9\u0BCD\u0BB1\u0BC1"):
                            raise lab9()
                        raise lab2()
                    except lab9: pass
                    self.cursor = self.limit - v_3
                    try:
                        # literal, line 232
                        if not self.eq_s_b(u"\u0BC1\u0BB3\u0BCD\u0BB3"):
                            raise lab10()
                        raise lab2()
                    except lab10: pass
                    self.cursor = self.limit - v_3
                    try:
                        # literal, line 233
                        if not self.eq_s_b(u"\u0BC1\u0B9F\u0BC8\u0BAF"):
                            raise lab11()
                        raise lab2()
                    except lab11: pass
                    self.cursor = self.limit - v_3
                    try:
                        # literal, line 234
                        if not self.eq_s_b(u"\u0BC1\u0B9F\u0BC8"):
                            raise lab12()
                        raise lab2()
                    except lab12: pass
                    self.cursor = self.limit - v_3
                    try:
                        # literal, line 235
                        if not self.eq_s_b(u"\u0BC6\u0BA9\u0BC1\u0BAE\u0BCD"):
                            raise lab13()
                        raise lab2()
                    except lab13: pass
                    self.cursor = self.limit - v_3
                    try:
                        # (, line 236
                        # literal, line 236
                        if not self.eq_s_b(u"\u0BB2\u0BCD\u0BB2"):
                            raise lab14()
                        # test, line 236
                        v_4 = self.limit - self.cursor
                        # (, line 236
                        # not, line 236
                        v_5 = self.limit - self.cursor
                        try:
                            # among, line 236
                            if self.find_among_b(TamilStemmer.a_16) == 0:
                                raise lab15()
                            raise lab14()
                        except lab15: pass
                        self.cursor = self.limit - v_5
                        self.cursor = self.limit - v_4
                        raise lab2()
                    except lab14: pass
                    self.cursor = self.limit - v_3
                    try:
                        # literal, line 237
                        if not self.eq_s_b(u"\u0BC6\u0BA9"):
                            raise lab16()
                        raise lab2()
                    except lab16: pass
                    self.cursor = self.limit - v_3
                    # literal, line 238
                    if not self.eq_s_b(u"\u0BBE\u0B95\u0BBF"):
                        raise lab1()
                except lab2: pass
                # ], line 238
                self.bra = self.cursor
                # <-, line 238
                if not self.slice_from(u"\u0BCD"):
                    return False
                # (, line 239
                # set found_a_match, line 239
                self.B_found_a_match = True
                self.cursor = self.limit - v_2
                raise lab0()
            except lab1: pass
            self.cursor = self.limit - v_1
            # test, line 242
            v_6 = self.limit - self.cursor
            # (, line 242
            # [, line 242
            self.ket = self.cursor
            # among, line 242
            if self.find_among_b(TamilStemmer.a_17) == 0:
                return False
            # ], line 255
            self.bra = self.cursor
            # delete, line 255
            if not self.slice_del():
                return False

            # (, line 256
            # set found_a_match, line 256
            self.B_found_a_match = True
            self.cursor = self.limit - v_6
        except lab0: pass
        self.cursor = self.limit_backward
        # do, line 259
        v_7 = self.cursor
        try:
            # call fix_endings, line 259
            if not self.__r_fix_endings():
                raise lab17()
        except lab17: pass
        self.cursor = v_7
        return True

    def __r_remove_vetrumai_urupukal(self):
        # (, line 262
        # unset found_a_match, line 263
        self.B_found_a_match = False
        # unset found_vetrumai_urupu, line 264
        self.B_found_vetrumai_urupu = False
        # call has_min_length, line 265
        if not self.__r_has_min_length():
            return False
        # backwards, line 266
        self.limit_backward = self.cursor
        self.cursor = self.limit
        # (, line 266
        # (, line 267
        # or, line 269
        try:
            v_1 = self.limit - self.cursor
            try:
                # test, line 268
                v_2 = self.limit - self.cursor
                # (, line 268
                # [, line 268
                self.ket = self.cursor
                # literal, line 268
                if not self.eq_s_b(u"\u0BA9\u0BC8"):
                    raise lab1()
                # ], line 268
                self.bra = self.cursor
                # delete, line 268
                if not self.slice_del():
                    return False

                self.cursor = self.limit - v_2
                raise lab0()
            except lab1: pass
            self.cursor = self.limit - v_1
            try:
                # test, line 270
                v_3 = self.limit - self.cursor
                # (, line 270
                # [, line 270
                self.ket = self.cursor
                # or, line 271
                try:
                    v_4 = self.limit - self.cursor
                    try:
                        # (, line 270
                        # or, line 270
                        try:
                            v_5 = self.limit - self.cursor
                            try:
                                # literal, line 270
                                if not self.eq_s_b(u"\u0BBF\u0BA9\u0BC8"):
                                    raise lab6()
                                raise lab5()
                            except lab6: pass
                            self.cursor = self.limit - v_5
                            # literal, line 271
                            if not self.eq_s_b(u"\u0BC8"):
                                raise lab4()
                        except lab5: pass
                        # (, line 271
                        # test, line 271
                        v_6 = self.limit - self.cursor
                        # not, line 271
                        v_7 = self.limit - self.cursor
                        try:
                            # among, line 271
                            if self.find_among_b(TamilStemmer.a_18) == 0:
                                raise lab7()
                            raise lab4()
                        except lab7: pass
                        self.cursor = self.limit - v_7
                        self.cursor = self.limit - v_6
                        raise lab3()
                    except lab4: pass
                    self.cursor = self.limit - v_4
                    # (, line 272
                    # literal, line 272
                    if not self.eq_s_b(u"\u0BC8"):
                        raise lab2()
                    # (, line 272
                    # test, line 272
                    v_8 = self.limit - self.cursor
                    # (, line 272
                    # among, line 272
                    if self.find_among_b(TamilStemmer.a_19) == 0:
                        raise lab2()
                    # literal, line 272
                    if not self.eq_s_b(u"\u0BCD"):
                        raise lab2()
                    self.cursor = self.limit - v_8
                except lab3: pass
                # ], line 273
                self.bra = self.cursor
                # <-, line 273
                if not self.slice_from(u"\u0BCD"):
                    return False
                self.cursor = self.limit - v_3
                raise lab0()
            except lab2: pass
            self.cursor = self.limit - v_1
            try:
                # test, line 276
                v_9 = self.limit - self.cursor
                # (, line 276
                # [, line 276
                self.ket = self.cursor
                # or, line 277
                try:
                    v_10 = self.limit - self.cursor
                    try:
                        # literal, line 277
                        if not self.eq_s_b(u"\u0BCA\u0B9F\u0BC1"):
                            raise lab10()
                        raise lab9()
                    except lab10: pass
                    self.cursor = self.limit - v_10
                    try:
                        # literal, line 278
                        if not self.eq_s_b(u"\u0BCB\u0B9F\u0BC1"):
                            raise lab11()
                        raise lab9()
                    except lab11: pass
                    self.cursor = self.limit - v_10
                    try:
                        # literal, line 279
                        if not self.eq_s_b(u"\u0BBF\u0BB2\u0BCD"):
                            raise lab12()
                        raise lab9()
                    except lab12: pass
                    self.cursor = self.limit - v_10
                    try:
                        # literal, line 280
                        if not self.eq_s_b(u"\u0BBF\u0BB1\u0BCD"):
                            raise lab13()
                        raise lab9()
                    except lab13: pass
                    self.cursor = self.limit - v_10
                    try:
                        # (, line 281
                        # literal, line 281
                        if not self.eq_s_b(u"\u0BBF\u0BA9\u0BCD"):
                            raise lab14()
                        # (, line 281
                        # test, line 281
                        v_11 = self.limit - self.cursor
                        # not, line 281
                        v_12 = self.limit - self.cursor
                        try:
                            # literal, line 281
                            if not self.eq_s_b(u"\u0BAE"):
                                raise lab15()
                            raise lab14()
                        except lab15: pass
                        self.cursor = self.limit - v_12
                        self.cursor = self.limit - v_11
                        raise lab9()
                    except lab14: pass
                    self.cursor = self.limit - v_10
                    try:
                        # literal, line 282
                        if not self.eq_s_b(u"\u0BBF\u0BA9\u0BCD\u0BB1\u0BC1"):
                            raise lab16()
                        raise lab9()
                    except lab16: pass
                    self.cursor = self.limit - v_10
                    try:
                        # literal, line 283
                        if not self.eq_s_b(u"\u0BBF\u0BB0\u0BC1\u0BA8\u0BCD\u0BA4\u0BC1"):
                            raise lab17()
                        raise lab9()
                    except lab17: pass
                    self.cursor = self.limit - v_10
                    try:
                        # literal, line 284
                        if not self.eq_s_b(u"\u0BB5\u0BBF\u0B9F"):
                            raise lab18()
                        raise lab9()
                    except lab18: pass
                    self.cursor = self.limit - v_10
                    try:
                        # (, line 285
                        if not self.I_length >= 7:
                            raise lab19()
                        # literal, line 285
                        if not self.eq_s_b(u"\u0BBF\u0B9F\u0BAE\u0BCD"):
                            raise lab19()
                        raise lab9()
                    except lab19: pass
                    self.cursor = self.limit - v_10
                    try:
                        # literal, line 286
                        if not self.eq_s_b(u"\u0BBE\u0BB2\u0BCD"):
                            raise lab20()
                        raise lab9()
                    except lab20: pass
                    self.cursor = self.limit - v_10
                    try:
                        # literal, line 287
                        if not self.eq_s_b(u"\u0BC1\u0B9F\u0BC8"):
                            raise lab21()
                        raise lab9()
                    except lab21: pass
                    self.cursor = self.limit - v_10
                    try:
                        # literal, line 288
                        if not self.eq_s_b(u"\u0BBE\u0BAE\u0BB2\u0BCD"):
                            raise lab22()
                        raise lab9()
                    except lab22: pass
                    self.cursor = self.limit - v_10
                    try:
                        # (, line 289
                        # literal, line 289
                        if not self.eq_s_b(u"\u0BB2\u0BCD"):
                            raise lab23()
                        # (, line 289
                        # test, line 289
                        v_13 = self.limit - self.cursor
                        # not, line 289
                        v_14 = self.limit - self.cursor
                        try:
                            # among, line 289
                            if self.find_among_b(TamilStemmer.a_20) == 0:
                                raise lab24()
                            raise lab23()
                        except lab24: pass
                        self.cursor = self.limit - v_14
                        self.cursor = self.limit - v_13
                        raise lab9()
                    except lab23: pass
                    self.cursor = self.limit - v_10
                    # literal, line 290
                    if not self.eq_s_b(u"\u0BC1\u0BB3\u0BCD"):
                        raise lab8()
                except lab9: pass
                # ], line 291
                self.bra = self.cursor
                # <-, line 291
                if not self.slice_from(u"\u0BCD"):
                    return False
                self.cursor = self.limit - v_9
                raise lab0()
            except lab8: pass
            self.cursor = self.limit - v_1
            try:
                # test, line 294
                v_15 = self.limit - self.cursor
                # (, line 294
                # [, line 294
                self.ket = self.cursor
                # or, line 295
                try:
                    v_16 = self.limit - self.cursor
                    try:
                        # literal, line 295
                        if not self.eq_s_b(u"\u0B95\u0BA3\u0BCD"):
                            raise lab27()
                        raise lab26()
                    except lab27: pass
                    self.cursor = self.limit - v_16
                    try:
                        # literal, line 296
                        if not self.eq_s_b(u"\u0BAE\u0BC1\u0BA9\u0BCD"):
                            raise lab28()
                        raise lab26()
                    except lab28: pass
                    self.cursor = self.limit - v_16
                    try:
                        # literal, line 297
                        if not self.eq_s_b(u"\u0BAE\u0BC7\u0BB2\u0BCD"):
                            raise lab29()
                        raise lab26()
                    except lab29: pass
                    self.cursor = self.limit - v_16
                    try:
                        # literal, line 298
                        if not self.eq_s_b(u"\u0BAE\u0BC7\u0BB1\u0BCD"):
                            raise lab30()
                        raise lab26()
                    except lab30: pass
                    self.cursor = self.limit - v_16
                    try:
                        # literal, line 299
                        if not self.eq_s_b(u"\u0B95\u0BC0\u0BB4\u0BCD"):
                            raise lab31()
                        raise lab26()
                    except lab31: pass
                    self.cursor = self.limit - v_16
                    try:
                        # literal, line 300
                        if not self.eq_s_b(u"\u0BAA\u0BBF\u0BA9\u0BCD"):
                            raise lab32()
                        raise lab26()
                    except lab32: pass
                    self.cursor = self.limit - v_16
                    # (, line 301
                    # literal, line 301
                    if not self.eq_s_b(u"\u0BA4\u0BC1"):
                        raise lab25()
                    # (, line 301
                    # test, line 301
                    v_17 = self.limit - self.cursor
                    # not, line 301
                    v_18 = self.limit - self.cursor
                    try:
                        # among, line 301
                        if self.find_among_b(TamilStemmer.a_21) == 0:
                            raise lab33()
                        raise lab25()
                    except lab33: pass
                    self.cursor = self.limit - v_18
                    self.cursor = self.limit - v_17
                except lab26: pass
                # ], line 302
                self.bra = self.cursor
                # delete, line 302
                if not self.slice_del():
                    return False

                self.cursor = self.limit - v_15
                raise lab0()
            except lab25: pass
            self.cursor = self.limit - v_1
            # test, line 305
            v_19 = self.limit - self.cursor
            # (, line 305
            # [, line 305
            self.ket = self.cursor
            # literal, line 305
            if not self.eq_s_b(u"\u0BC0"):
                return False
            # ], line 305
            self.bra = self.cursor
            # <-, line 305
            if not self.slice_from(u"\u0BBF"):
                return False
            self.cursor = self.limit - v_19
        except lab0: pass
        # (, line 307
        # set found_a_match, line 307
        self.B_found_a_match = True
        # (, line 308
        # set found_vetrumai_urupu, line 308
        self.B_found_vetrumai_urupu = True
        # do, line 309
        v_20 = self.limit - self.cursor
        try:
            # (, line 309
            # [, line 309
            self.ket = self.cursor
            # literal, line 309
            if not self.eq_s_b(u"\u0BBF\u0BA9\u0BCD"):
                raise lab34()
            # ], line 309
            self.bra = self.cursor
            # <-, line 309
            if not self.slice_from(u"\u0BCD"):
                return False
        except lab34: pass
        self.cursor = self.limit - v_20
        self.cursor = self.limit_backward
        # do, line 311
        v_21 = self.cursor
        try:
            # call fix_endings, line 311
            if not self.__r_fix_endings():
                raise lab35()
        except lab35: pass
        self.cursor = v_21
        return True

    def __r_remove_tense_suffixes(self):
        # (, line 314
        # set found_a_match, line 315
        self.B_found_a_match = True
        # repeat, line 316
        try:
            while True:
                try:
                    v_1 = self.cursor
                    try:
                        # (, line 316
                        # Boolean test found_a_match, line 316
                        if not self.B_found_a_match:
                            raise lab2()
                        # (, line 316
                        # do, line 316
                        v_2 = self.cursor
                        try:
                            # call remove_tense_suffix, line 316
                            if not self.__r_remove_tense_suffix():
                                raise lab3()
                        except lab3: pass
                        self.cursor = v_2
                        raise lab1()
                    except lab2: pass
                    self.cursor = v_1
                    raise lab0()
                except lab1: pass
        except lab0: pass
        return True

    def __r_remove_tense_suffix(self):
        # (, line 319
        # unset found_a_match, line 320
        self.B_found_a_match = False
        # call has_min_length, line 321
        if not self.__r_has_min_length():
            return False
        # backwards, line 322
        self.limit_backward = self.cursor
        self.cursor = self.limit
        # (, line 322
        # do, line 323
        v_1 = self.limit - self.cursor
        try:
            # (, line 323
            # or, line 330
            try:
                v_2 = self.limit - self.cursor
                try:
                    # test, line 324
                    v_3 = self.limit - self.cursor
                    # (, line 324
                    # [, line 324
                    self.ket = self.cursor
                    # among, line 324
                    if self.find_among_b(TamilStemmer.a_22) == 0:
                        raise lab2()
                    # ], line 327
                    self.bra = self.cursor
                    # delete, line 327
                    if not self.slice_del():
                        return False

                    # (, line 328
                    # set found_a_match, line 328
                    self.B_found_a_match = True
                    self.cursor = self.limit - v_3
                    raise lab1()
                except lab2: pass
                self.cursor = self.limit - v_2
                try:
                    # test, line 331
                    v_4 = self.limit - self.cursor
                    # (, line 331
                    # [, line 331
                    self.ket = self.cursor
                    # or, line 332
                    try:
                        v_5 = self.limit - self.cursor
                        try:
                            # literal, line 332
                            if not self.eq_s_b(u"\u0BAE\u0BBE\u0BB0\u0BCD"):
                                raise lab5()
                            raise lab4()
                        except lab5: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 333
                            if not self.eq_s_b(u"\u0BAE\u0BBF\u0BA9\u0BCD"):
                                raise lab6()
                            raise lab4()
                        except lab6: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 334
                            if not self.eq_s_b(u"\u0BA9\u0BA9\u0BCD"):
                                raise lab7()
                            raise lab4()
                        except lab7: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 335
                            if not self.eq_s_b(u"\u0BA9\u0BBE\u0BA9\u0BCD"):
                                raise lab8()
                            raise lab4()
                        except lab8: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 336
                            if not self.eq_s_b(u"\u0BA9\u0BBE\u0BB3\u0BCD"):
                                raise lab9()
                            raise lab4()
                        except lab9: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 337
                            if not self.eq_s_b(u"\u0BA9\u0BBE\u0BB0\u0BCD"):
                                raise lab10()
                            raise lab4()
                        except lab10: pass
                        self.cursor = self.limit - v_5
                        try:
                            # (, line 338
                            # literal, line 338
                            if not self.eq_s_b(u"\u0BB5\u0BA9\u0BCD"):
                                raise lab11()
                            # test, line 338
                            v_6 = self.limit - self.cursor
                            # (, line 338
                            # not, line 338
                            v_7 = self.limit - self.cursor
                            try:
                                # among, line 338
                                if self.find_among_b(TamilStemmer.a_23) == 0:
                                    raise lab12()
                                raise lab11()
                            except lab12: pass
                            self.cursor = self.limit - v_7
                            self.cursor = self.limit - v_6
                            raise lab4()
                        except lab11: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 339
                            if not self.eq_s_b(u"\u0BA9\u0BB3\u0BCD"):
                                raise lab13()
                            raise lab4()
                        except lab13: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 340
                            if not self.eq_s_b(u"\u0BB5\u0BB3\u0BCD"):
                                raise lab14()
                            raise lab4()
                        except lab14: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 341
                            if not self.eq_s_b(u"\u0BA9\u0BB0\u0BCD"):
                                raise lab15()
                            raise lab4()
                        except lab15: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 342
                            if not self.eq_s_b(u"\u0BB5\u0BB0\u0BCD"):
                                raise lab16()
                            raise lab4()
                        except lab16: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 343
                            if not self.eq_s_b(u"\u0BA9"):
                                raise lab17()
                            raise lab4()
                        except lab17: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 343
                            if not self.eq_s_b(u"\u0BAA"):
                                raise lab18()
                            raise lab4()
                        except lab18: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 343
                            if not self.eq_s_b(u"\u0B95"):
                                raise lab19()
                            raise lab4()
                        except lab19: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 343
                            if not self.eq_s_b(u"\u0BA4"):
                                raise lab20()
                            raise lab4()
                        except lab20: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 343
                            if not self.eq_s_b(u"\u0BAF"):
                                raise lab21()
                            raise lab4()
                        except lab21: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 344
                            if not self.eq_s_b(u"\u0BAA\u0BA9\u0BCD"):
                                raise lab22()
                            raise lab4()
                        except lab22: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 345
                            if not self.eq_s_b(u"\u0BAA\u0BB3\u0BCD"):
                                raise lab23()
                            raise lab4()
                        except lab23: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 346
                            if not self.eq_s_b(u"\u0BAA\u0BB0\u0BCD"):
                                raise lab24()
                            raise lab4()
                        except lab24: pass
                        self.cursor = self.limit - v_5
                        try:
                            # (, line 347
                            # literal, line 347
                            if not self.eq_s_b(u"\u0BA4\u0BC1"):
                                raise lab25()
                            # (, line 347
                            # test, line 347
                            v_8 = self.limit - self.cursor
                            # not, line 347
                            v_9 = self.limit - self.cursor
                            try:
                                # among, line 347
                                if self.find_among_b(TamilStemmer.a_24) == 0:
                                    raise lab26()
                                raise lab25()
                            except lab26: pass
                            self.cursor = self.limit - v_9
                            self.cursor = self.limit - v_8
                            raise lab4()
                        except lab25: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 348
                            if not self.eq_s_b(u"\u0BBF\u0BB1\u0BCD\u0BB1\u0BC1"):
                                raise lab27()
                            raise lab4()
                        except lab27: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 349
                            if not self.eq_s_b(u"\u0BAA\u0BAE\u0BCD"):
                                raise lab28()
                            raise lab4()
                        except lab28: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 350
                            if not self.eq_s_b(u"\u0BA9\u0BAE\u0BCD"):
                                raise lab29()
                            raise lab4()
                        except lab29: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 351
                            if not self.eq_s_b(u"\u0BA4\u0BC1\u0BAE\u0BCD"):
                                raise lab30()
                            raise lab4()
                        except lab30: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 352
                            if not self.eq_s_b(u"\u0BB1\u0BC1\u0BAE\u0BCD"):
                                raise lab31()
                            raise lab4()
                        except lab31: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 353
                            if not self.eq_s_b(u"\u0B95\u0BC1\u0BAE\u0BCD"):
                                raise lab32()
                            raise lab4()
                        except lab32: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 354
                            if not self.eq_s_b(u"\u0BA9\u0BC6\u0BA9\u0BCD"):
                                raise lab33()
                            raise lab4()
                        except lab33: pass
                        self.cursor = self.limit - v_5
                        try:
                            # literal, line 355
                            if not self.eq_s_b(u"\u0BA9\u0BC8"):
                                raise lab34()
                            raise lab4()
                        except lab34: pass
                        self.cursor = self.limit - v_5
                        # literal, line 356
                        if not self.eq_s_b(u"\u0BB5\u0BC8"):
                            raise lab3()
                    except lab4: pass
                    # ], line 357
                    self.bra = self.cursor
                    # delete, line 357
                    if not self.slice_del():
                        return False

                    # (, line 358
                    # set found_a_match, line 358
                    self.B_found_a_match = True
                    self.cursor = self.limit - v_4
                    raise lab1()
                except lab3: pass
                self.cursor = self.limit - v_2
                try:
                    # test, line 361
                    v_10 = self.limit - self.cursor
                    # (, line 361
                    # [, line 361
                    self.ket = self.cursor
                    # or, line 362
                    try:
                        v_11 = self.limit - self.cursor
                        try:
                            # (, line 362
                            # literal, line 362
                            if not self.eq_s_b(u"\u0BBE\u0BA9\u0BCD"):
                                raise lab37()
                            # test, line 362
                            v_12 = self.limit - self.cursor
                            # (, line 362
                            # not, line 362
                            v_13 = self.limit - self.cursor
                            try:
                                # literal, line 362
                                if not self.eq_s_b(u"\u0B9A"):
                                    raise lab38()
                                raise lab37()
                            except lab38: pass
                            self.cursor = self.limit - v_13
                            self.cursor = self.limit - v_12
                            raise lab36()
                        except lab37: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 363
                            if not self.eq_s_b(u"\u0BBE\u0BB3\u0BCD"):
                                raise lab39()
                            raise lab36()
                        except lab39: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 364
                            if not self.eq_s_b(u"\u0BBE\u0BB0\u0BCD"):
                                raise lab40()
                            raise lab36()
                        except lab40: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 365
                            if not self.eq_s_b(u"\u0BC7\u0BA9\u0BCD"):
                                raise lab41()
                            raise lab36()
                        except lab41: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 366
                            if not self.eq_s_b(u"\u0BBE"):
                                raise lab42()
                            raise lab36()
                        except lab42: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 367
                            if not self.eq_s_b(u"\u0BBE\u0BAE\u0BCD"):
                                raise lab43()
                            raise lab36()
                        except lab43: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 368
                            if not self.eq_s_b(u"\u0BC6\u0BAE\u0BCD"):
                                raise lab44()
                            raise lab36()
                        except lab44: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 369
                            if not self.eq_s_b(u"\u0BC7\u0BAE\u0BCD"):
                                raise lab45()
                            raise lab36()
                        except lab45: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 370
                            if not self.eq_s_b(u"\u0BCB\u0BAE\u0BCD"):
                                raise lab46()
                            raise lab36()
                        except lab46: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 371
                            if not self.eq_s_b(u"\u0B95\u0BC1\u0BAE\u0BCD"):
                                raise lab47()
                            raise lab36()
                        except lab47: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 372
                            if not self.eq_s_b(u"\u0BA4\u0BC1\u0BAE\u0BCD"):
                                raise lab48()
                            raise lab36()
                        except lab48: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 373
                            if not self.eq_s_b(u"\u0B9F\u0BC1\u0BAE\u0BCD"):
                                raise lab49()
                            raise lab36()
                        except lab49: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 374
                            if not self.eq_s_b(u"\u0BB1\u0BC1\u0BAE\u0BCD"):
                                raise lab50()
                            raise lab36()
                        except lab50: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 375
                            if not self.eq_s_b(u"\u0BBE\u0BAF\u0BCD"):
                                raise lab51()
                            raise lab36()
                        except lab51: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 376
                            if not self.eq_s_b(u"\u0BA9\u0BC6\u0BA9\u0BCD"):
                                raise lab52()
                            raise lab36()
                        except lab52: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 377
                            if not self.eq_s_b(u"\u0BA9\u0BBF\u0BB0\u0BCD"):
                                raise lab53()
                            raise lab36()
                        except lab53: pass
                        self.cursor = self.limit - v_11
                        try:
                            # literal, line 378
                            if not self.eq_s_b(u"\u0BC0\u0BB0\u0BCD"):
                                raise lab54()
                            raise lab36()
                        except lab54: pass
                        self.cursor = self.limit - v_11
                        # literal, line 379
                        if not self.eq_s_b(u"\u0BC0\u0BAF\u0BB0\u0BCD"):
                            raise lab35()
                    except lab36: pass
                    # ], line 380
                    self.bra = self.cursor
                    # <-, line 380
                    if not self.slice_from(u"\u0BCD"):
                        return False
                    # (, line 381
                    # set found_a_match, line 381
                    self.B_found_a_match = True
                    self.cursor = self.limit - v_10
                    raise lab1()
                except lab35: pass
                self.cursor = self.limit - v_2
                # test, line 384
                v_14 = self.limit - self.cursor
                # (, line 384
                # (, line 384
                # [, line 384
                self.ket = self.cursor
                # or, line 384
                try:
                    v_15 = self.limit - self.cursor
                    try:
                        # literal, line 384
                        if not self.eq_s_b(u"\u0B95\u0BC1"):
                            raise lab56()
                        raise lab55()
                    except lab56: pass
                    self.cursor = self.limit - v_15
                    # literal, line 384
                    if not self.eq_s_b(u"\u0BA4\u0BC1"):
                        raise lab0()
                except lab55: pass
                # (, line 384
                # test, line 384
                v_16 = self.limit - self.cursor
                # literal, line 384
                if not self.eq_s_b(u"\u0BCD"):
                    raise lab0()
                self.cursor = self.limit - v_16
                # ], line 384
                self.bra = self.cursor
                # delete, line 384
                if not self.slice_del():
                    return False

                # (, line 385
                # set found_a_match, line 385
                self.B_found_a_match = True
                self.cursor = self.limit - v_14
            except lab1: pass
        except lab0: pass
        self.cursor = self.limit - v_1
        # do, line 388
        v_17 = self.limit - self.cursor
        try:
            # (, line 388
            # [, line 388
            self.ket = self.cursor
            # among, line 388
            if self.find_among_b(TamilStemmer.a_25) == 0:
                raise lab57()
            # ], line 395
            self.bra = self.cursor
            # delete, line 395
            if not self.slice_del():
                return False

            # (, line 396
            # set found_a_match, line 396
            self.B_found_a_match = True
        except lab57: pass
        self.cursor = self.limit - v_17
        self.cursor = self.limit_backward
        # do, line 399
        v_18 = self.cursor
        try:
            # call fix_endings, line 399
            if not self.__r_fix_endings():
                raise lab58()
        except lab58: pass
        self.cursor = v_18
        return True

    def _stem(self):
        # (, line 402
        # unset found_vetrumai_urupu, line 403
        self.B_found_vetrumai_urupu = False
        # do, line 404
        v_1 = self.cursor
        try:
            # call fix_ending, line 404
            if not self.__r_fix_ending():
                raise lab0()
        except lab0: pass
        self.cursor = v_1
        # call has_min_length, line 405
        if not self.__r_has_min_length():
            return False
        # do, line 406
        v_2 = self.cursor
        try:
            # call remove_question_prefixes, line 406
            if not self.__r_remove_question_prefixes():
                raise lab1()
        except lab1: pass
        self.cursor = v_2
        # do, line 407
        v_3 = self.cursor
        try:
            # call remove_pronoun_prefixes, line 407
            if not self.__r_remove_pronoun_prefixes():
                raise lab2()
        except lab2: pass
        self.cursor = v_3
        # do, line 408
        v_4 = self.cursor
        try:
            # call remove_question_suffixes, line 408
            if not self.__r_remove_question_suffixes():
                raise lab3()
        except lab3: pass
        self.cursor = v_4
        # do, line 409
        v_5 = self.cursor
        try:
            # call remove_um, line 409
            if not self.__r_remove_um():
                raise lab4()
        except lab4: pass
        self.cursor = v_5
        # do, line 410
        v_6 = self.cursor
        try:
            # call remove_common_word_endings, line 410
            if not self.__r_remove_common_word_endings():
                raise lab5()
        except lab5: pass
        self.cursor = v_6
        # do, line 411
        v_7 = self.cursor
        try:
            # call remove_vetrumai_urupukal, line 411
            if not self.__r_remove_vetrumai_urupukal():
                raise lab6()
        except lab6: pass
        self.cursor = v_7
        # do, line 412
        v_8 = self.cursor
        try:
            # call remove_plural_suffix, line 412
            if not self.__r_remove_plural_suffix():
                raise lab7()
        except lab7: pass
        self.cursor = v_8
        # do, line 413
        v_9 = self.cursor
        try:
            # call remove_command_suffixes, line 413
            if not self.__r_remove_command_suffixes():
                raise lab8()
        except lab8: pass
        self.cursor = v_9
        # do, line 414
        v_10 = self.cursor
        try:
            # call remove_tense_suffixes, line 414
            if not self.__r_remove_tense_suffixes():
                raise lab9()
        except lab9: pass
        self.cursor = v_10
        return True


class lab0(BaseException): pass


class lab1(BaseException): pass


class lab2(BaseException): pass


class lab3(BaseException): pass


class lab4(BaseException): pass


class lab5(BaseException): pass


class lab6(BaseException): pass


class lab7(BaseException): pass


class lab8(BaseException): pass


class lab9(BaseException): pass


class lab10(BaseException): pass


class lab11(BaseException): pass


class lab12(BaseException): pass


class lab13(BaseException): pass


class lab14(BaseException): pass


class lab15(BaseException): pass


class lab16(BaseException): pass


class lab17(BaseException): pass


class lab18(BaseException): pass


class lab19(BaseException): pass


class lab20(BaseException): pass


class lab21(BaseException): pass


class lab22(BaseException): pass


class lab23(BaseException): pass


class lab24(BaseException): pass


class lab25(BaseException): pass


class lab26(BaseException): pass


class lab27(BaseException): pass


class lab28(BaseException): pass


class lab29(BaseException): pass


class lab30(BaseException): pass


class lab31(BaseException): pass


class lab32(BaseException): pass


class lab33(BaseException): pass


class lab34(BaseException): pass


class lab35(BaseException): pass


class lab36(BaseException): pass


class lab37(BaseException): pass


class lab38(BaseException): pass


class lab39(BaseException): pass


class lab40(BaseException): pass


class lab41(BaseException): pass


class lab42(BaseException): pass


class lab43(BaseException): pass


class lab44(BaseException): pass


class lab45(BaseException): pass


class lab46(BaseException): pass


class lab47(BaseException): pass


class lab48(BaseException): pass


class lab49(BaseException): pass


class lab50(BaseException): pass


class lab51(BaseException): pass


class lab52(BaseException): pass


class lab53(BaseException): pass


class lab54(BaseException): pass


class lab55(BaseException): pass


class lab56(BaseException): pass


class lab57(BaseException): pass


class lab58(BaseException): pass
